import type { OutcomeCode, ResolutionCode } from '../../../dto';

export const JUDGMENT_DIRECTION_KEYS = [
  'JUDGMENT_DIRECT',
  'JUDGMENT_SUSPICION',
  'JUDGMENT_INSUFFICIENT',
  'JUDGMENT_TRUTH_ATTACK',
  'JUDGMENT_IRRELEVANT',
] as const;
export type JudgmentDirectionKey = (typeof JUDGMENT_DIRECTION_KEYS)[number];

export const ENDING_DIRECTION_KEYS = [
  'ENDING_POLAROID',
  'ENDING_TRANSFER_STAMP',
  'ENDING_BGM_MUTE',
  'ENDING_CARD_AND_KNOCK',
  'ENDING_OVERWORK',
] as const;
export type EndingDirectionKey = (typeof ENDING_DIRECTION_KEYS)[number];

/** Resolution direction is declarative; renderers do not branch on codes. */
export const RESOLUTION_DIRECTION_TABLE: Readonly<Record<ResolutionCode, JudgmentDirectionKey>> = {
  R_DIRECT_CONTRADICTION: 'JUDGMENT_DIRECT',
  R_INDIRECT_SUSPICION: 'JUDGMENT_SUSPICION',
  R_INSUFFICIENT_GROUNDS: 'JUDGMENT_INSUFFICIENT',
  R_TRUTH_ATTACKED: 'JUDGMENT_TRUTH_ATTACK',
  R_IRRELEVANT_EVIDENCE: 'JUDGMENT_IRRELEVANT',
  R_CONFIRM_LOCKED: 'JUDGMENT_INSUFFICIENT',
  R_CONFIRM_PROVISIONAL: 'JUDGMENT_SUSPICION',
  R_CONFIRM_CONFLICT: 'JUDGMENT_TRUTH_ATTACK',
  R_QUERY_SUCCESS: 'JUDGMENT_SUSPICION',
  R_QUERY_BLOCKED: 'JUDGMENT_INSUFFICIENT',
  R_CLARIFY_SUCCESS: 'JUDGMENT_SUSPICION',
  R_CLARIFY_NOOP: 'JUDGMENT_INSUFFICIENT',
  R_COMMIT_SUCCESS: 'JUDGMENT_DIRECT',
  R_COMMIT_REFUSED: 'JUDGMENT_INSUFFICIENT',
  R_FORENSIC_REVEALED: 'JUDGMENT_DIRECT',
  R_PRESSURE_APPLIED: 'JUDGMENT_SUSPICION',
  R_PRESSURE_BACKFIRE: 'JUDGMENT_TRUTH_ATTACK',
  R_RECOVER_APPLIED: 'JUDGMENT_SUSPICION',
  R_SPECIAL_APPLIED: 'JUDGMENT_DIRECT',
  R_ACTION_INVALID: 'JUDGMENT_INSUFFICIENT',
  R_PROCEDURE_VIOLATION: 'JUDGMENT_TRUTH_ATTACK',
};

/** The five ending treatments are selected only through this data table. */
export const OUTCOME_DIRECTION_TABLE: Readonly<Record<OutcomeCode, EndingDirectionKey>> = {
  O_FULL_STATEMENT: 'ENDING_POLAROID',
  O_ARREST: 'ENDING_TRANSFER_STAMP',
  O_COERCED_CONFESSION: 'ENDING_BGM_MUTE',
  O_COUNSEL_INTERVENTION: 'ENDING_CARD_AND_KNOCK',
  O_OVERWORK: 'ENDING_OVERWORK',
};

export function directionForResolution(code: ResolutionCode): JudgmentDirectionKey {
  return RESOLUTION_DIRECTION_TABLE[code];
}

export function directionForOutcome(code: OutcomeCode): EndingDirectionKey {
  return OUTCOME_DIRECTION_TABLE[code];
}
